version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: clinica_medica_db
    environment:
      POSTGRES_DB: clinica_medica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clinica_network

volumes:
  postgres_data:

networks:
  clinica_network: